import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-vercel-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "products_details" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "products_options" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "products_options" ALTER COLUMN "type_id" SET DATA TYPE uuid;
  ALTER TABLE "products_variants_options" ALTER COLUMN "type_id" SET DATA TYPE uuid;
  ALTER TABLE "products_variants_options" ALTER COLUMN "value_id" SET DATA TYPE uuid;
  ALTER TABLE "products_variants" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "products_variants" ALTER COLUMN "image_id" SET DATA TYPE uuid;
  ALTER TABLE "products_categories" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "products_categories" ALTER COLUMN "category_id" SET DATA TYPE uuid;
  ALTER TABLE "products" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "products" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "products" ALTER COLUMN "shop_id" SET DATA TYPE uuid;
  ALTER TABLE "products_rels" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "products_rels" ALTER COLUMN "media_id" SET DATA TYPE uuid;
  ALTER TABLE "products_rels" ALTER COLUMN "product_option_values_id" SET DATA TYPE uuid;
  ALTER TABLE "_products_v_version_details" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_products_v_version_details" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "_products_v_version_details" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "_products_v_version_options" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_products_v_version_options" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "_products_v_version_options" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "_products_v_version_options" ALTER COLUMN "type_id" SET DATA TYPE uuid;
  ALTER TABLE "_products_v_version_variants_options" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_products_v_version_variants_options" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "_products_v_version_variants_options" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "_products_v_version_variants_options" ALTER COLUMN "type_id" SET DATA TYPE uuid;
  ALTER TABLE "_products_v_version_variants_options" ALTER COLUMN "value_id" SET DATA TYPE uuid;
  ALTER TABLE "_products_v_version_variants" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_products_v_version_variants" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "_products_v_version_variants" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "_products_v_version_variants" ALTER COLUMN "image_id" SET DATA TYPE uuid;
  ALTER TABLE "_products_v_version_categories" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_products_v_version_categories" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "_products_v_version_categories" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "_products_v_version_categories" ALTER COLUMN "category_id" SET DATA TYPE uuid;
  ALTER TABLE "_products_v" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "_products_v" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "_products_v" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_products_v" ALTER COLUMN "version_shop_id" SET DATA TYPE uuid;
  ALTER TABLE "_products_v_rels" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_products_v_rels" ALTER COLUMN "media_id" SET DATA TYPE uuid;
  ALTER TABLE "_products_v_rels" ALTER COLUMN "product_option_values_id" SET DATA TYPE uuid;
  ALTER TABLE "pages_hero_links" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "pages_blocks_cta" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "pages_blocks_carousel_slides" ALTER COLUMN "image_id" SET DATA TYPE uuid;
  ALTER TABLE "pages_blocks_carousel" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "pages_blocks_content" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "pages_blocks_media_block" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "pages_blocks_media_block" ALTER COLUMN "media_id" SET DATA TYPE uuid;
  ALTER TABLE "pages_blocks_archive" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "pages_blocks_form_block" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "pages_blocks_form_block" ALTER COLUMN "form_id" SET DATA TYPE uuid;
  ALTER TABLE "pages" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "pages" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "pages" ALTER COLUMN "shop_id" SET DATA TYPE uuid;
  ALTER TABLE "pages" ALTER COLUMN "hero_media_id" SET DATA TYPE uuid;
  ALTER TABLE "pages" ALTER COLUMN "meta_image_id" SET DATA TYPE uuid;
  ALTER TABLE "pages_rels" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "pages_rels" ALTER COLUMN "pages_id" SET DATA TYPE uuid;
  ALTER TABLE "pages_rels" ALTER COLUMN "posts_id" SET DATA TYPE uuid;
  ALTER TABLE "pages_rels" ALTER COLUMN "categories_id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v_version_hero_links" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v_version_hero_links" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v_version_hero_links" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "_pages_v_blocks_cta" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v_blocks_cta" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v_blocks_cta" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "_pages_v_blocks_carousel_slides" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v_blocks_carousel_slides" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v_blocks_carousel_slides" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "_pages_v_blocks_carousel_slides" ALTER COLUMN "image_id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v_blocks_carousel" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v_blocks_carousel" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v_blocks_carousel" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "_pages_v_blocks_content" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v_blocks_content" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v_blocks_content" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "_pages_v_blocks_media_block" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v_blocks_media_block" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v_blocks_media_block" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "_pages_v_blocks_media_block" ALTER COLUMN "media_id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v_blocks_archive" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v_blocks_archive" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v_blocks_archive" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "_pages_v_blocks_form_block" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v_blocks_form_block" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v_blocks_form_block" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "_pages_v_blocks_form_block" ALTER COLUMN "form_id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "_pages_v" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v" ALTER COLUMN "version_shop_id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v" ALTER COLUMN "version_hero_media_id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v" ALTER COLUMN "version_meta_image_id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v_rels" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v_rels" ALTER COLUMN "pages_id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v_rels" ALTER COLUMN "posts_id" SET DATA TYPE uuid;
  ALTER TABLE "_pages_v_rels" ALTER COLUMN "categories_id" SET DATA TYPE uuid;
  ALTER TABLE "product_categories" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "product_categories" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "product_categories" ALTER COLUMN "shop_id" SET DATA TYPE uuid;
  ALTER TABLE "orders_items" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "orders_items" ALTER COLUMN "image_id" SET DATA TYPE uuid;
  ALTER TABLE "orders" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "orders" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "orders" ALTER COLUMN "shop_id" SET DATA TYPE uuid;
  ALTER TABLE "orders" ALTER COLUMN "customer_id" SET DATA TYPE uuid;
  ALTER TABLE "orders" ALTER COLUMN "shipping_address_address_id" SET DATA TYPE uuid;
  ALTER TABLE "product_options" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "product_options" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "product_options" ALTER COLUMN "shop_id" SET DATA TYPE uuid;
  ALTER TABLE "product_option_values" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "product_option_values" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "product_option_values" ALTER COLUMN "shop_id" SET DATA TYPE uuid;
  ALTER TABLE "product_option_values" ALTER COLUMN "product_option_type_id" SET DATA TYPE uuid;
  ALTER TABLE "media" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "media" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "media" ALTER COLUMN "shop_id" SET DATA TYPE uuid;
  ALTER TABLE "transactions" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "transactions" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "transactions" ALTER COLUMN "shop_id" SET DATA TYPE uuid;
  ALTER TABLE "transactions" ALTER COLUMN "user_id" SET DATA TYPE uuid;
  ALTER TABLE "transactions" ALTER COLUMN "order_id" SET DATA TYPE uuid;
  ALTER TABLE "addresses" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "addresses" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "addresses" ALTER COLUMN "user_id" SET DATA TYPE uuid;
  ALTER TABLE "customers_sessions" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "customers" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "customers" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "posts_populated_authors" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "posts" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "posts" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "posts" ALTER COLUMN "shop_id" SET DATA TYPE uuid;
  ALTER TABLE "posts" ALTER COLUMN "hero_image_id" SET DATA TYPE uuid;
  ALTER TABLE "posts" ALTER COLUMN "meta_image_id" SET DATA TYPE uuid;
  ALTER TABLE "posts_rels" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "posts_rels" ALTER COLUMN "posts_id" SET DATA TYPE uuid;
  ALTER TABLE "posts_rels" ALTER COLUMN "categories_id" SET DATA TYPE uuid;
  ALTER TABLE "posts_rels" ALTER COLUMN "users_id" SET DATA TYPE uuid;
  ALTER TABLE "_posts_v_version_populated_authors" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_posts_v_version_populated_authors" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "_posts_v_version_populated_authors" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "_posts_v" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "_posts_v" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "_posts_v" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_posts_v" ALTER COLUMN "version_shop_id" SET DATA TYPE uuid;
  ALTER TABLE "_posts_v" ALTER COLUMN "version_hero_image_id" SET DATA TYPE uuid;
  ALTER TABLE "_posts_v" ALTER COLUMN "version_meta_image_id" SET DATA TYPE uuid;
  ALTER TABLE "_posts_v_rels" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "_posts_v_rels" ALTER COLUMN "posts_id" SET DATA TYPE uuid;
  ALTER TABLE "_posts_v_rels" ALTER COLUMN "categories_id" SET DATA TYPE uuid;
  ALTER TABLE "_posts_v_rels" ALTER COLUMN "users_id" SET DATA TYPE uuid;
  ALTER TABLE "categories_breadcrumbs" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "categories_breadcrumbs" ALTER COLUMN "doc_id" SET DATA TYPE uuid;
  ALTER TABLE "categories" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "categories" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "categories" ALTER COLUMN "shop_id" SET DATA TYPE uuid;
  ALTER TABLE "categories" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "shops" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "shops" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "users_roles" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "users_roles" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "users_roles" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "users_shops" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "users_shops" ALTER COLUMN "shop_id" SET DATA TYPE uuid;
  ALTER TABLE "users_sessions" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "users" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "users" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "header_nav_items" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "header" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "header" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "header" ALTER COLUMN "shop_id" SET DATA TYPE uuid;
  ALTER TABLE "header_rels" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "header_rels" ALTER COLUMN "pages_id" SET DATA TYPE uuid;
  ALTER TABLE "header_rels" ALTER COLUMN "posts_id" SET DATA TYPE uuid;
  ALTER TABLE "footer_nav_items" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "footer" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "footer" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "footer" ALTER COLUMN "shop_id" SET DATA TYPE uuid;
  ALTER TABLE "footer_rels" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "footer_rels" ALTER COLUMN "pages_id" SET DATA TYPE uuid;
  ALTER TABLE "footer_rels" ALTER COLUMN "posts_id" SET DATA TYPE uuid;
  ALTER TABLE "payment_providers" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "payment_providers" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "payment_providers" ALTER COLUMN "shop_id" SET DATA TYPE uuid;
  ALTER TABLE "shop_layout" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "shop_layout" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "shop_layout" ALTER COLUMN "shop_id" SET DATA TYPE uuid;
  ALTER TABLE "shop_settings_available_currencies" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "shop_settings_available_currencies" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "shop_settings_available_currencies" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "shop_settings" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "shop_settings" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "shop_settings" ALTER COLUMN "shop_id" SET DATA TYPE uuid;
  ALTER TABLE "redirects" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "redirects" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "redirects_rels" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "redirects_rels" ALTER COLUMN "pages_id" SET DATA TYPE uuid;
  ALTER TABLE "redirects_rels" ALTER COLUMN "posts_id" SET DATA TYPE uuid;
  ALTER TABLE "forms_blocks_checkbox" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "forms_blocks_country" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "forms_blocks_email" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "forms_blocks_message" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "forms_blocks_number" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "forms_blocks_select" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "forms_blocks_state" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "forms_blocks_text" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "forms_blocks_textarea" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "forms_emails" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "forms" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "forms" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "form_submissions_submission_data" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "form_submissions" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "form_submissions" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "form_submissions" ALTER COLUMN "form_id" SET DATA TYPE uuid;
  ALTER TABLE "search_categories" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "search" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "search" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "search" ALTER COLUMN "meta_image_id" SET DATA TYPE uuid;
  ALTER TABLE "search_rels" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "search_rels" ALTER COLUMN "posts_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_jobs_log" ALTER COLUMN "_parent_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_jobs" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "payload_jobs" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "payload_locked_documents" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "products_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "pages_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "product_categories_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "orders_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "product_options_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "product_option_values_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "media_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "transactions_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "addresses_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "customers_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "posts_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "categories_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "shops_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "users_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "header_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "footer_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "payment_providers_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "shop_layout_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "shop_settings_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "redirects_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "forms_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "form_submissions_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "search_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "payload_jobs_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_preferences" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "payload_preferences" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
  ALTER TABLE "payload_preferences_rels" ALTER COLUMN "parent_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_preferences_rels" ALTER COLUMN "customers_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_preferences_rels" ALTER COLUMN "users_id" SET DATA TYPE uuid;
  ALTER TABLE "payload_migrations" ALTER COLUMN "id" SET DATA TYPE uuid;
  ALTER TABLE "payload_migrations" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "products_details" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "products_options" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "products_options" ALTER COLUMN "type_id" SET DATA TYPE integer;
  ALTER TABLE "products_variants_options" ALTER COLUMN "type_id" SET DATA TYPE integer;
  ALTER TABLE "products_variants_options" ALTER COLUMN "value_id" SET DATA TYPE integer;
  ALTER TABLE "products_variants" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "products_variants" ALTER COLUMN "image_id" SET DATA TYPE integer;
  ALTER TABLE "products_categories" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "products_categories" ALTER COLUMN "category_id" SET DATA TYPE integer;
  ALTER TABLE "products" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "products" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "products" ALTER COLUMN "shop_id" SET DATA TYPE integer;
  ALTER TABLE "products_rels" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "products_rels" ALTER COLUMN "media_id" SET DATA TYPE integer;
  ALTER TABLE "products_rels" ALTER COLUMN "product_option_values_id" SET DATA TYPE integer;
  ALTER TABLE "_products_v_version_details" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "_products_v_version_details" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "_products_v_version_details" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "_products_v_version_options" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "_products_v_version_options" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "_products_v_version_options" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "_products_v_version_options" ALTER COLUMN "type_id" SET DATA TYPE integer;
  ALTER TABLE "_products_v_version_variants_options" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "_products_v_version_variants_options" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "_products_v_version_variants_options" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "_products_v_version_variants_options" ALTER COLUMN "type_id" SET DATA TYPE integer;
  ALTER TABLE "_products_v_version_variants_options" ALTER COLUMN "value_id" SET DATA TYPE integer;
  ALTER TABLE "_products_v_version_variants" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "_products_v_version_variants" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "_products_v_version_variants" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "_products_v_version_variants" ALTER COLUMN "image_id" SET DATA TYPE integer;
  ALTER TABLE "_products_v_version_categories" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "_products_v_version_categories" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "_products_v_version_categories" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "_products_v_version_categories" ALTER COLUMN "category_id" SET DATA TYPE integer;
  ALTER TABLE "_products_v" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "_products_v" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "_products_v" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "_products_v" ALTER COLUMN "version_shop_id" SET DATA TYPE integer;
  ALTER TABLE "_products_v_rels" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "_products_v_rels" ALTER COLUMN "media_id" SET DATA TYPE integer;
  ALTER TABLE "_products_v_rels" ALTER COLUMN "product_option_values_id" SET DATA TYPE integer;
  ALTER TABLE "pages_hero_links" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "pages_blocks_cta" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "pages_blocks_carousel_slides" ALTER COLUMN "image_id" SET DATA TYPE integer;
  ALTER TABLE "pages_blocks_carousel" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "pages_blocks_content" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "pages_blocks_media_block" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "pages_blocks_media_block" ALTER COLUMN "media_id" SET DATA TYPE integer;
  ALTER TABLE "pages_blocks_archive" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "pages_blocks_form_block" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "pages_blocks_form_block" ALTER COLUMN "form_id" SET DATA TYPE integer;
  ALTER TABLE "pages" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "pages" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "pages" ALTER COLUMN "shop_id" SET DATA TYPE integer;
  ALTER TABLE "pages" ALTER COLUMN "hero_media_id" SET DATA TYPE integer;
  ALTER TABLE "pages" ALTER COLUMN "meta_image_id" SET DATA TYPE integer;
  ALTER TABLE "pages_rels" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "pages_rels" ALTER COLUMN "pages_id" SET DATA TYPE integer;
  ALTER TABLE "pages_rels" ALTER COLUMN "posts_id" SET DATA TYPE integer;
  ALTER TABLE "pages_rels" ALTER COLUMN "categories_id" SET DATA TYPE integer;
  ALTER TABLE "_pages_v_version_hero_links" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "_pages_v_version_hero_links" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "_pages_v_version_hero_links" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_cta" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "_pages_v_blocks_cta" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "_pages_v_blocks_cta" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_carousel_slides" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "_pages_v_blocks_carousel_slides" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "_pages_v_blocks_carousel_slides" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_carousel_slides" ALTER COLUMN "image_id" SET DATA TYPE integer;
  ALTER TABLE "_pages_v_blocks_carousel" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "_pages_v_blocks_carousel" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "_pages_v_blocks_carousel" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_content" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "_pages_v_blocks_content" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "_pages_v_blocks_content" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_media_block" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "_pages_v_blocks_media_block" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "_pages_v_blocks_media_block" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_media_block" ALTER COLUMN "media_id" SET DATA TYPE integer;
  ALTER TABLE "_pages_v_blocks_archive" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "_pages_v_blocks_archive" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "_pages_v_blocks_archive" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_form_block" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "_pages_v_blocks_form_block" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "_pages_v_blocks_form_block" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_form_block" ALTER COLUMN "form_id" SET DATA TYPE integer;
  ALTER TABLE "_pages_v" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "_pages_v" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "_pages_v" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "_pages_v" ALTER COLUMN "version_shop_id" SET DATA TYPE integer;
  ALTER TABLE "_pages_v" ALTER COLUMN "version_hero_media_id" SET DATA TYPE integer;
  ALTER TABLE "_pages_v" ALTER COLUMN "version_meta_image_id" SET DATA TYPE integer;
  ALTER TABLE "_pages_v_rels" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "_pages_v_rels" ALTER COLUMN "pages_id" SET DATA TYPE integer;
  ALTER TABLE "_pages_v_rels" ALTER COLUMN "posts_id" SET DATA TYPE integer;
  ALTER TABLE "_pages_v_rels" ALTER COLUMN "categories_id" SET DATA TYPE integer;
  ALTER TABLE "product_categories" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "product_categories" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "product_categories" ALTER COLUMN "shop_id" SET DATA TYPE integer;
  ALTER TABLE "orders_items" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "orders_items" ALTER COLUMN "image_id" SET DATA TYPE integer;
  ALTER TABLE "orders" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "orders" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "orders" ALTER COLUMN "shop_id" SET DATA TYPE integer;
  ALTER TABLE "orders" ALTER COLUMN "customer_id" SET DATA TYPE integer;
  ALTER TABLE "orders" ALTER COLUMN "shipping_address_address_id" SET DATA TYPE integer;
  ALTER TABLE "product_options" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "product_options" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "product_options" ALTER COLUMN "shop_id" SET DATA TYPE integer;
  ALTER TABLE "product_option_values" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "product_option_values" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "product_option_values" ALTER COLUMN "shop_id" SET DATA TYPE integer;
  ALTER TABLE "product_option_values" ALTER COLUMN "product_option_type_id" SET DATA TYPE integer;
  ALTER TABLE "media" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "media" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "media" ALTER COLUMN "shop_id" SET DATA TYPE integer;
  ALTER TABLE "transactions" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "transactions" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "transactions" ALTER COLUMN "shop_id" SET DATA TYPE integer;
  ALTER TABLE "transactions" ALTER COLUMN "user_id" SET DATA TYPE integer;
  ALTER TABLE "transactions" ALTER COLUMN "order_id" SET DATA TYPE integer;
  ALTER TABLE "addresses" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "addresses" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "addresses" ALTER COLUMN "user_id" SET DATA TYPE integer;
  ALTER TABLE "customers_sessions" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "customers" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "customers" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "posts_populated_authors" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "posts" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "posts" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "posts" ALTER COLUMN "shop_id" SET DATA TYPE integer;
  ALTER TABLE "posts" ALTER COLUMN "hero_image_id" SET DATA TYPE integer;
  ALTER TABLE "posts" ALTER COLUMN "meta_image_id" SET DATA TYPE integer;
  ALTER TABLE "posts_rels" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "posts_rels" ALTER COLUMN "posts_id" SET DATA TYPE integer;
  ALTER TABLE "posts_rels" ALTER COLUMN "categories_id" SET DATA TYPE integer;
  ALTER TABLE "posts_rels" ALTER COLUMN "users_id" SET DATA TYPE integer;
  ALTER TABLE "_posts_v_version_populated_authors" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "_posts_v_version_populated_authors" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "_posts_v_version_populated_authors" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "_posts_v" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "_posts_v" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "_posts_v" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "_posts_v" ALTER COLUMN "version_shop_id" SET DATA TYPE integer;
  ALTER TABLE "_posts_v" ALTER COLUMN "version_hero_image_id" SET DATA TYPE integer;
  ALTER TABLE "_posts_v" ALTER COLUMN "version_meta_image_id" SET DATA TYPE integer;
  ALTER TABLE "_posts_v_rels" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "_posts_v_rels" ALTER COLUMN "posts_id" SET DATA TYPE integer;
  ALTER TABLE "_posts_v_rels" ALTER COLUMN "categories_id" SET DATA TYPE integer;
  ALTER TABLE "_posts_v_rels" ALTER COLUMN "users_id" SET DATA TYPE integer;
  ALTER TABLE "categories_breadcrumbs" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "categories_breadcrumbs" ALTER COLUMN "doc_id" SET DATA TYPE integer;
  ALTER TABLE "categories" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "categories" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "categories" ALTER COLUMN "shop_id" SET DATA TYPE integer;
  ALTER TABLE "categories" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "shops" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "shops" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "users_roles" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "users_roles" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "users_roles" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "users_shops" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "users_shops" ALTER COLUMN "shop_id" SET DATA TYPE integer;
  ALTER TABLE "users_sessions" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "users" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "users" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "header_nav_items" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "header" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "header" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "header" ALTER COLUMN "shop_id" SET DATA TYPE integer;
  ALTER TABLE "header_rels" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "header_rels" ALTER COLUMN "pages_id" SET DATA TYPE integer;
  ALTER TABLE "header_rels" ALTER COLUMN "posts_id" SET DATA TYPE integer;
  ALTER TABLE "footer_nav_items" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "footer" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "footer" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "footer" ALTER COLUMN "shop_id" SET DATA TYPE integer;
  ALTER TABLE "footer_rels" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "footer_rels" ALTER COLUMN "pages_id" SET DATA TYPE integer;
  ALTER TABLE "footer_rels" ALTER COLUMN "posts_id" SET DATA TYPE integer;
  ALTER TABLE "payment_providers" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "payment_providers" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "payment_providers" ALTER COLUMN "shop_id" SET DATA TYPE integer;
  ALTER TABLE "shop_layout" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "shop_layout" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "shop_layout" ALTER COLUMN "shop_id" SET DATA TYPE integer;
  ALTER TABLE "shop_settings_available_currencies" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "shop_settings_available_currencies" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "shop_settings_available_currencies" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "shop_settings" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "shop_settings" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "shop_settings" ALTER COLUMN "shop_id" SET DATA TYPE integer;
  ALTER TABLE "redirects" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "redirects" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "redirects_rels" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "redirects_rels" ALTER COLUMN "pages_id" SET DATA TYPE integer;
  ALTER TABLE "redirects_rels" ALTER COLUMN "posts_id" SET DATA TYPE integer;
  ALTER TABLE "forms_blocks_checkbox" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "forms_blocks_country" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "forms_blocks_email" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "forms_blocks_message" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "forms_blocks_number" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "forms_blocks_select" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "forms_blocks_state" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "forms_blocks_text" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "forms_blocks_textarea" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "forms_emails" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "forms" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "forms" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "form_submissions_submission_data" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "form_submissions" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "form_submissions" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "form_submissions" ALTER COLUMN "form_id" SET DATA TYPE integer;
  ALTER TABLE "search_categories" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "search" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "search" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "search" ALTER COLUMN "meta_image_id" SET DATA TYPE integer;
  ALTER TABLE "search_rels" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "search_rels" ALTER COLUMN "posts_id" SET DATA TYPE integer;
  ALTER TABLE "payload_jobs_log" ALTER COLUMN "_parent_id" SET DATA TYPE integer;
  ALTER TABLE "payload_jobs" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "payload_jobs" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "payload_locked_documents" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "payload_locked_documents" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "products_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "pages_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "product_categories_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "orders_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "product_options_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "product_option_values_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "media_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "transactions_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "addresses_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "customers_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "posts_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "categories_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "shops_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "users_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "header_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "footer_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "payment_providers_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "shop_layout_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "shop_settings_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "redirects_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "forms_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "form_submissions_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "search_id" SET DATA TYPE integer;
  ALTER TABLE "payload_locked_documents_rels" ALTER COLUMN "payload_jobs_id" SET DATA TYPE integer;
  ALTER TABLE "payload_preferences" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "payload_preferences" ALTER COLUMN "id" DROP DEFAULT;
  ALTER TABLE "payload_preferences_rels" ALTER COLUMN "parent_id" SET DATA TYPE integer;
  ALTER TABLE "payload_preferences_rels" ALTER COLUMN "customers_id" SET DATA TYPE integer;
  ALTER TABLE "payload_preferences_rels" ALTER COLUMN "users_id" SET DATA TYPE integer;
  ALTER TABLE "payload_migrations" ALTER COLUMN "id" SET DATA TYPE serial;
  ALTER TABLE "payload_migrations" ALTER COLUMN "id" DROP DEFAULT;`)
}
